let musicList = [
    {
        name: "سورة الفاتحة",
        artist: "آڈیو القرآن",
        img: "img/sname_1_t.png",
        src: "audio/Sorat-no-01.mp3",
        love: false,
    },
	{
        name: "سورة البقرة",
        artist: "آڈیو القرآن",
        img: "img/sname_2_t.png",
        src: "audio/Sorat-no-02.mp3",
        love: false,
    },
	{
        name: "سورة آل عمران",
        artist: "آڈیو القرآن",
        img: "img/sname_3_t.png",
        src: "audio/Sorat-no-03.mp3",
        love: false,
    },
	{
        name: "سورة النساء",
        artist: "آڈیو القرآن",
        img: "img/sname_4_t.png",
        src: "audio/Sorat-no-04.mp3",
        love: false,
    },
	{
        name: "سورة المائدة",
        artist: "آڈیو القرآن",
        img: "img/sname_5_t.png",
        src: "audio/Sorat-no-05.mp3",
        love: false,
    },
	{
        name: "سورة الأنعام",
        artist: "آڈیو القرآن",
        img: "img/sname_6_t.png",
        src: "audio/Sorat-no-06.mp3",
        love: false,
    },
	{
        name: "سورة الأعراف",
        artist: "آڈیو القرآن",
        img: "img/sname_7_t.png",
        src: "audio/Sorat-no-07.mp3",
        love: false,
    },
	{
        name: "سورة الأنفال ",
        artist: "آڈیو القرآن",
        img: "img/sname_8_t.png",
        src: "audio/Sorat-no-08.mp3",
        love: false,
    },
	{
        name: "سورة التوبة",
        artist: "آڈیو القرآن",
        img: "img/sname_9_t.png",
        src: "audio/Sorat-no-09.mp3",
        love: false,
    },
	{
        name: "سورة يونس",
        artist: "آڈیو القرآن",
        img: "img/sname_10_t.png",
        src: "audio/Sorat-no-10.mp3",
        love: false,
    },
	{
        name: "سورة هود",
        artist: "آڈیو القرآن",
        img: "img/sname_11_t.png",
        src: "audio/Sorat-no-11.mp3",
        love: false,
    },
	{
        name: "سورة يوسف",
        artist: "آڈیو القرآن",
        img: "img/sname_12_t.png",
        src: "audio/Sorat-no-12.mp3",
        love: false,
    },
	{
        name: "سورة الرعد",
        artist: "آڈیو القرآن",
        img: "img/sname_13_t.png",
        src: "audio/Sorat-no-13.mp3",
        love: false,
    },
	{
        name: "سورة إبراهيم",
        artist: "آڈیو القرآن",
        img: "img/sname_14_t.png",
        src: "audio/Sorat-no-14.mp3",
        love: false,
    },
	{
        name: "سورة الحجر",
        artist: "آڈیو القرآن",
        img: "img/sname_15_t.png",
        src: "audio/Sorat-no-15.mp3",
        love: false,
    },
	{
        name: "سورة النحل",
        artist: "آڈیو القرآن",
        img: "img/sname_16_t.png",
        src: "audio/Sorat-no-16.mp3",
        love: false,
    },
	{
        name: "سورة الإسراء",
        artist: "آڈیو القرآن",
        img: "img/sname_17_t.png",
        src: "audio/Sorat-no-17.mp3",
        love: false,
    },
	{
        name: "سورة الكهف",
        artist: "آڈیو القرآن",
        img: "img/sname_18_t.png",
        src: "audio/Sorat-no-18.mp3",
        love: false,
    },
	{
        name: "سورة مريم",
        artist: "آڈیو القرآن",
        img: "img/sname_19_t.png",
        src: "audio/Sorat-no-19.mp3",
        love: false,
    },
	{
        name: "سورة طه ",
        artist: "آڈیو القرآن",
        img: "img/sname_20_t.png",
        src: "audio/Sorat-no-20.mp3",
        love: false,
    },
	{
        name: "سورة الأنبياء",
        artist: "آڈیو القرآن",
        img: "img/sname_21_t.png",
        src: "audio/Sorat-no-21.mp3",
        love: false,
    },
	{
        name: "سورة الحج",
        artist: "آڈیو القرآن",
        img: "img/sname_22_t.png",
        src: "audio/Sorat-no-22.mp3",
        love: false,
    },
	{
        name: "سورة المؤمنون",
        artist: "آڈیو القرآن",
        img: "img/sname_23_t.png",
        src: "audio/Sorat-no-23.mp3",
        love: false,
    },
	{
        name: "سورة النور",
        artist: "آڈیو القرآن",
        img: "img/sname_24_t.png",
        src: "audio/Sorat-no-24.mp3",
        love: false,
    },
	{
        name: "سورة الفرقان",
        artist: "آڈیو القرآن",
        img: "img/sname_25_t.png",
        src: "audio/Sorat-no-25.mp3",
        love: false,
    },
	{
        name: "سورة الشعراء",
        artist: "آڈیو القرآن",
        img: "img/sname_26_t.png",
        src: "audio/Sorat-no-26.mp3",
        love: false,
    },
	{
        name: "سورة النمل",
        artist: "آڈیو القرآن",
        img: "img/sname_27_t.png",
        src: "audio/Sorat-no-27.mp3",
        love: false,
    },
	{
        name: "سورة القصص",
        artist: "آڈیو القرآن",
        img: "img/sname_28_t.png",
        src: "audio/Sorat-no-28.mp3",
        love: false,
    },
	{
        name: "سورة العنكبوت",
        artist: "آڈیو القرآن",
        img: "img/sname_29_t.png",
        src: "audio/Sorat-no-29.mp3",
        love: false,
    },
	{
        name: "سورة الروم",
        artist: "آڈیو القرآن",
        img: "img/sname_30_t.png",
        src: "audio/Sorat-no-30.mp3",
        love: false,
    },
	{
        name: "سورة لقمان",
        artist: "آڈیو القرآن",
        img: "img/sname_31_t.png",
        src: "audio/Sorat-no-31.mp3",
        love: false,
    },
	{
        name: "سورة السجدة ",
        artist: "آڈیو القرآن",
        img: "img/sname_32_t.png",
        src: "audio/Sorat-no-32.mp3",
        love: false,
    },
	{
        name: "سورة الأحزاب",
        artist: "آڈیو القرآن",
        img: "img/sname_33_t.png",
        src: "audio/Sorat-no-33.mp3",
        love: false,
    },
	{
        name: "سورة سبأ",
        artist: "آڈیو القرآن",
        img: "img/sname_34_t.png",
        src: "audio/Sorat-no-34.mp3",
        love: false,
    },
	{
        name: "سورة فاطر",
        artist: "آڈیو القرآن",
        img: "img/sname_35_t.png",
        src: "audio/Sorat-no-35.mp3",
        love: false,
    },
	{
        name: "سورة يسین",
        artist: "آڈیو القرآن",
        img: "img/sname_36_t.png",
        src: "audio/Sorat-no-36.mp3",
        love: false,
    },
	{
        name: "سورة الصافات",
        artist: "آڈیو القرآن",
        img: "img/sname_37_t.png",
        src: "audio/Sorat-no-37.mp3",
        love: false,
    },
	{
        name: "سورة ص",
        artist: "آڈیو القرآن",
        img: "img/sname_38_t.png",
        src: "audio/Sorat-no-38.mp3",
        love: false,
    },
	{
        name: "سورة الزمر",
        artist: "آڈیو القرآن",
        img: "img/sname_39_t.png",
        src: "audio/Sorat-no-39.mp3",
        love: false,
    },
	{
        name: "سورة غافر ",
        artist: "آڈیو القرآن",
        img: "img/sname_40_t.png",
        src: "audio/Sorat-no-40.mp3",
        love: false,
    },
	{
        name: "سورة فصلت",
        artist: "آڈیو القرآن",
        img: "img/sname_41_t.png",
        src: "audio/Sorat-no-41.mp3",
        love: false,
    },
	{
        name: "سورة الشورى",
        artist: "آڈیو القرآن",
        img: "img/sname_42_t.png",
        src: "audio/Sorat-no-42.mp3",
        love: false,
    },
	{
        name: "سورة الزخرف",
        artist: "آڈیو القرآن",
        img: "img/sname_43_t.png",
        src: "audio/Sorat-no-43.mp3",
        love: false,
    },
	{
        name: "سورة الدخان",
        artist: "آڈیو القرآن",
        img: "img/sname_44_t.png",
        src: "audio/Sorat-no-44.mp3",
        love: false,
    },
	{
        name: "سورة الجاثية",
        artist: "آڈیو القرآن",
        img: "img/sname_45_t.png",
        src: "audio/Sorat-no-45.mp3",
        love: false,
    },
	{
        name: "سورة الأحقاف",
        artist: "آڈیو القرآن",
        img: "img/sname_46_t.png",
        src: "audio/Sorat-no-46.mp3",
        love: false,
    },
	{
        name: "سورة محمد",
        artist: "آڈیو القرآن",
        img: "img/sname_47_t.png",
        src: "audio/Sorat-no-47.mp3",
        love: false,
    },
	{
        name: "سورة الفتح ",
        artist: "آڈیو القرآن",
        img: "img/sname_48_t.png",
        src: "audio/Sorat-no-48.mp3",
        love: false,
    },
	{
        name: "سورة الحجرات",
        artist: "آڈیو القرآن",
        img: "img/sname_49_t.png",
        src: "audio/Sorat-no-49.mp3",
        love: false,
    },
	{
        name: "سورة ق",
        artist: "آڈیو القرآن",
        img: "img/sname_50_t.png",
        src: "audio/Sorat-no-50.mp3",
        love: false,
    },
	{
        name: "سورة الذاريات",
        artist: "آڈیو القرآن",
        img: "img/sname_51_t.png",
        src: "audio/Sorat-no-51.mp3",
        love: false,
    },
	{
        name: "سورة الطور",
        artist: "آڈیو القرآن",
        img: "img/sname_52_t.png",
        src: "audio/Sorat-no-52.mp3",
        love: false,
    },
	{
        name: "سورة النجم",
        artist: "آڈیو القرآن",
        img: "img/sname_53_t.png",
        src: "audio/Sorat-no-53.mp3",
        love: false,
    },
	{
        name: "سورة القمر",
        artist: "آڈیو القرآن",
        img: "img/sname_54_t.png",
        src: "audio/Sorat-no-54.mp3",
        love: false,
    },
	{
        name: "سورة الرحمن",
        artist: "آڈیو القرآن",
        img: "img/sname_55_t.png",
        src: "audio/Sorat-no-55.mp3",
        love: false,
    },
	{
        name: "سورة الواقعة ",
        artist: "آڈیو القرآن",
        img: "img/sname_56_t.png",
        src: "audio/Sorat-no-56.mp3",
        love: false,
    },
	{
        name: "سورة الحديد",
        artist: "آڈیو القرآن",
        img: "img/sname_57_t.png",
        src: "audio/Sorat-no-57.mp3",
        love: false,
    },
	{
        name: "سورة المجادلة",
        artist: "آڈیو القرآن",
        img: "img/sname_58_t.png",
        src: "audio/Sorat-no-58.mp3",
        love: false,
    },
	{
        name: "سورة الحشر",
        artist: "آڈیو القرآن",
        img: "img/sname_59_t.png",
        src: "audio/Sorat-no-59.mp3",
        love: false,
    },
	{
        name: "سورة الممتحنة",
        artist: "آڈیو القرآن",
        img: "img/sname_60_t.png",
        src: "audio/Sorat-no-60.mp3",
        love: false,
    },
	{
        name: "سورة الصف",
        artist: "آڈیو القرآن",
        img: "img/sname_61_t.png",
        src: "audio/Sorat-no-61.mp3",
        love: false,
    },
	{
        name: "سورة الجمعة",
        artist: "آڈیو القرآن",
        img: "img/sname_62_t.png",
        src: "audio/Sorat-no-62.mp3",
        love: false,
    },
	{
        name: "سورة المنافقون",
        artist: "آڈیو القرآن",
        img: "img/sname_63_t.png",
        src: "audio/Sorat-no-63.mp3",
        love: false,
    },
	{
        name: "سورة التغابن ",
        artist: "آڈیو القرآن",
        img: "img/sname_64_t.png",
        src: "audio/Sorat-no-64.mp3",
        love: false,
    },
	{
        name: "سورة الطلاق",
        artist: "آڈیو القرآن",
        img: "img/sname_65_t.png",
        src: "audio/Sorat-no-65.mp3",
        love: false,
    },
	{
        name: "سورة التحريم",
        artist: "آڈیو القرآن",
        img: "img/sname_66_t.png",
        src: "audio/Sorat-no-66.mp3",
        love: false,
    },
	{
        name: "سورة الملك",
        artist: "آڈیو القرآن",
        img: "img/sname_67_t.png",
        src: "audio/Sorat-no-67.mp3",
        love: false,
    },
	{
        name: "سورة القلم",
        artist: "آڈیو القرآن",
        img: "img/sname_68_t.png",
        src: "audio/Sorat-no-68.mp3",
        love: false,
    },
	{
        name: "سورة الحاقة",
        artist: "آڈیو القرآن",
        img: "img/sname_69_t.png",
        src: "audio/Sorat-no-69.mp3",
        love: false,
    },
	{
        name: "سورة المعارج",
        artist: "آڈیو القرآن",
        img: "img/sname_70_t.png",
        src: "audio/Sorat-no-70.mp3",
        love: false,
    },
	{
        name: "سورة نوح",
        artist: "آڈیو القرآن",
        img: "img/sname_71_t.png",
        src: "audio/Sorat-no-71.mp3",
        love: false,
    },
	{
        name: "سورة الجن",
        artist: "آڈیو القرآن",
        img: "img/sname_72_t.png",
        src: "audio/Sorat-no-72.mp3",
        love: false,
    },
	{
        name: "سورة المزمل",
        artist: "آڈیو القرآن",
        img: "img/sname_73_t.png",
        src: "audio/Sorat-no-73.mp3",
        love: false,
    },
	{
        name: "سورة المدثر",
        artist: "آڈیو القرآن",
        img: "img/sname_74_t.png",
        src: "audio/Sorat-no-74.mp3",
        love: false,
    },
	{
        name: "سورة القيامة",
        artist: "آڈیو القرآن",
        img: "img/sname_75_t.png",
        src: "audio/Sorat-no-75.mp3",
        love: false,
    },
	{
        name: "سورة الإنسان",
        artist: "آڈیو القرآن",
        img: "img/sname_76_t.png",
        src: "audio/Sorat-no-76.mp3",
        love: false,
    },
	{
        name: "سورة المرسلات",
        artist: "آڈیو القرآن",
        img: "img/sname_77_t.png",
        src: "audio/Sorat-no-77.mp3",
        love: false,
    },
	{
        name: "سورة النبأ",
        artist: "آڈیو القرآن",
        img: "img/sname_78_t.png",
        src: "audio/Sorat-no-78.mp3",
        love: false,
    },
	{
        name: "سورة النازعات",
        artist: "آڈیو القرآن",
        img: "img/sname_79_t.png",
        src: "audio/Sorat-no-79.mp3",
        love: false,
    },
	{
        name: "سورة عبس",
        artist: "آڈیو القرآن",
        img: "img/sname_80_t.png",
        src: "audio/Sorat-no-80.mp3",
        love: false,
    },
	{
        name: "سورة التكوير",
        artist: "آڈیو القرآن",
        img: "img/sname_81_t.png",
        src: "audio/Sorat-no-81.mp3",
        love: false,
    },
	{
        name: "سورة الإنفطار",
        artist: "آڈیو القرآن",
        img: "img/sname_82_t.png",
        src: "audio/Sorat-no-82.mp3",
        love: false,
    },
	{
        name: "سورة المطففين",
        artist: "آڈیو القرآن",
        img: "img/sname_83_t.png",
        src: "audio/Sorat-no-83.mp3",
        love: false,
    },
	{
        name: "سورة الإنشقاق",
        artist: "آڈیو القرآن",
        img: "img/sname_84_t.png",
        src: "audio/Sorat-no-84.mp3",
        love: false,
    },
	{
        name: "سورة البروج",
        artist: "آڈیو القرآن",
        img: "img/sname_85_t.png",
        src: "audio/Sorat-no-85.mp3",
        love: false,
    },
	{
        name: "سورة الطارق",
        artist: "آڈیو القرآن",
        img: "img/sname_86_t.png",
        src: "audio/Sorat-no-86.mp3",
        love: false,
    },
	{
        name: "سورة الأعلى",
        artist: "آڈیو القرآن",
        img: "img/sname_87_t.png",
        src: "audio/Sorat-no-87.mp3",
        love: false,
    },
	{
        name: "سورة الغاشية ",
        artist: "آڈیو القرآن",
        img: "img/sname_88_t.png",
        src: "audio/Sorat-no-88.mp3",
        love: false,
    },
	{
        name: "سورة الفجر",
        artist: "آڈیو القرآن",
        img: "img/sname_89_t.png",
        src: "audio/Sorat-no-89.mp3",
        love: false,
    },
	{
        name: "سورة البلد",
        artist: "آڈیو القرآن",
        img: "img/sname_90_t.png",
        src: "audio/Sorat-no-90.mp3",
        love: false,
    },
	{
        name: "سورة الشمس",
        artist: "آڈیو القرآن",
        img: "img/sname_91_t.png",
        src: "audio/Sorat-no-91.mp3",
        love: false,
    },
	{
        name: "سورة الليل",
        artist: "آڈیو القرآن",
        img: "img/sname_92_t.png",
        src: "audio/Sorat-no-92.mp3",
        love: false,
    },
	{
        name: "سورة الضحى",
        artist: "آڈیو القرآن",
        img: "img/sname_93_t.png",
        src: "audio/Sorat-no-93.mp3",
        love: false,
    },
	{
        name: "سورة الشرح",
        artist: "آڈیو القرآن",
        img: "img/sname_94_t.png",
        src: "audio/Sorat-no-94.mp3",
        love: false,
    },
	{
        name: "سورة التين",
        artist: "آڈیو القرآن",
        img: "img/sname_95_t.png",
        src: "audio/Sorat-no-95.mp3",
        love: false,
    },
	{
        name: "سورة العلق",
        artist: "آڈیو القرآن",
        img: "img/sname_96_t.png",
        src: "audio/Sorat-no-96.mp3",
        love: false,
    },
	{
        name: "سورة القدر",
        artist: "آڈیو القرآن",
        img: "img/sname_97_t.png",
        src: "audio/Sorat-no-97.mp3",
        love: false,
    },
	{
        name: "سورة البينة",
        artist: "آڈیو القرآن",
        img: "img/sname_98_t.png",
        src: "audio/Sorat-no-98.mp3",
        love: false,
    },
	{
        name: "سورة الزلزلة",
        artist: "آڈیو القرآن",
        img: "img/sname_99_t.png",
        src: "audio/Sorat-no-99.mp3",
        love: false,
    },
	{
        name: "سورة العاديات",
        artist: "آڈیو القرآن",
        img: "img/sname_100_t.png",
        src: "audio/Sorat-no-100.mp3",
        love: false,
    },
	{
        name: "سورة القارعة",
        artist: "آڈیو القرآن",
        img: "img/sname_101_t.png",
        src: "audio/Sorat-no-101.mp3",
        love: false,
    },
	{
        name: "سورة التكاثر",
        artist: "آڈیو القرآن",
        img: "img/sname_102_t.png",
        src: "audio/Sorat-no-102.mp3",
        love: false,
    },
	{
        name: "سورة العصر",
        artist: "آڈیو القرآن",
        img: "img/sname_103_t.png",
        src: "audio/Sorat-no-103.mp3",
        love: false,
    },
	{
        name: "سورة الهمزة",
        artist: "آڈیو القرآن",
        img: "img/sname_104_t.png",
        src: "audio/Sorat-no-104.mp3",
        love: false,
    },
	{
        name: "سورة الفيل",
        artist: "آڈیو القرآن",
        img: "img/sname_105_t.png",
        src: "audio/Sorat-no-105.mp3",
        love: false,
    },
	{
        name: "سورة قريش",
        artist: "آڈیو القرآن",
        img: "img/sname_106_t.png",
        src: "audio/Sorat-no-106.mp3",
        love: false,
    },
	{
        name: "سورة الماعون",
        artist: "آڈیو القرآن",
        img: "img/sname_107_t.png",
        src: "audio/Sorat-no-107.mp3",
        love: false,
    },
	{
        name: "سورة الكوثر",
        artist: "آڈیو القرآن",
        img: "img/sname_108_t.png",
        src: "audio/Sorat-no-108.mp3",
        love: false,
    },
	{
        name: "سورة الكافرون",
        artist: "آڈیو القرآن",
        img: "img/sname_109_t.png",
        src: "audio/Sorat-no-109.mp3",
        love: false,
    },
	{
        name: "سورة النصر",
        artist: "آڈیو القرآن",
        img: "img/sname_110_t.png",
        src: "audio/Sorat-no-110.mp3",
        love: false,
    },
    {
        name: "سورة المسد",
        artist: "آڈیو القرآن",
        img: "img/sname_111_t.png",
        src: "audio/Sorat-no-111.mp3",
        love: false,
    },
	{
        name: "سورة الإخلاص",
        artist: "آڈیو القرآن",
        img: "img/sname_112_t.png",
        src: "audio/Sorat-no-112.mp3",
        love: false,
    },
    {
        name: "سورة الفلق",
        artist: "آڈیو القرآن",
        img: "img/sname_113_t.png",
        src: "audio/Sorat-no-113.mp3",
        love: false,
    },
    {
        name: "سورة الناس",
        artist: "آڈیو القرآن",
        img: "img/sname_114_t.png",
        src: "audio/Sorat-no-114.mp3",
        love: false,
    },
    {
        name: "دعا ختم القرآن",
        artist: "آڈیو القرآن",
        img: "img/quran.jpg",
        src: "audio/Sorat-no-115.mp3",
        love: false,
    },
];
